### ISSUE TITLE
missinggo modules confusion

### ISSUE THREAD

**Issue by myleshorton** [anacrolix/missinggo#17] opened 2019-07-25 22:14 UTC
I'm getting this with missinggo as an indirect dependency of lantern's http-proxy -- seems not to like this line in go.mod:

```
module github.com/anacrolix/missinggo/v2 
```

```
$ GO111MODULE=on go get github.com/anacrolix/missinggo@master
go: finding github.com/anacrolix/missinggo master
go: github.com/anacrolix/missinggo@v0.0.0-20190427052756-3d85a149c812: go.mod has post-v0 module path "github.com/anacrolix/missinggo/v2" at revision 3d85a149c812
go: error loading module requirements
```

**Comment by anacrolix** [comment] 2019-07-25 23:52
I believe that's correct behaviour. master is now on `v2`, you likely want `go get github.com/anacrolix/missinggo@latest`, or to let it update normally as part of a `go get -u` (which it won't do, because v1.1 is the latest v1 release as at the time of this comment).

**Comment by anacrolix** [comment] 2019-07-26 00:27
I've pushed v1.1.1 if you want to test this theory.

**Comment by myleshorton** [comment] 2019-07-26 15:07
Ah so this is interesting. It only doesn't work when specifying `GOOS=linux GOARCH=amd64` --

in the second CLI `make build` here I modified the Makefile to include those. Will keep investigating.

```
[http-proxy-lantern (master)]$ make build
mkdir -p bin && \
	GO111MODULE=on go build -o bin/http-proxy \
	-ldflags="-X main.revision=c9b3c86" \
	github.com/getlantern/http-proxy-lantern/http-proxy && \
	file bin/http-proxy
bin/http-proxy: Mach-O 64-bit executable x86_64
[http-proxy-lantern (master)]$ make build
mkdir -p bin && \
	GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o bin/http-proxy \
	-ldflags="-X main.revision=c9b3c86" \
	github.com/getlantern/http-proxy-lantern/http-proxy && \
	file bin/http-proxy
build github.com/getlantern/http-proxy-lantern/http-proxy: cannot find module for path github.com/anacrolix/missinggo
make: *** [build] Error 1
```

**Comment by myleshorton** [comment] 2019-07-26 15:09
`GOOS=linux GOARCH=amd64 go get -u github.com/anacrolix/missinggo@v1.1.1` doesn't help...

**Comment by myleshorton** [comment] 2019-07-26 16:51
Got this working with using the docker build targets -- this might be the entire reason those exist!

**Comment by anacrolix** [comment] 2019-07-30 01:17
Something about cross-compiling seems to confuse it. I'm able to reproduce the problem, and no amount of fiddling with replace directives, or updates to dependencies seems to help.

**Comment by anacrolix** [comment] 2019-07-30 01:45
I think it has something to do with cgo and go-libutp.

**Comment by anacrolix** [comment] 2019-12-18 00:11
@myleshorton Is this still causing problems?

**Comment by anacrolix** [comment] 2023-02-16 10:24
I'll close this, reopen if it still comes up.

**Closed by anacrolix** 2023-02-16 10:24 UTC
